name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Archive
        run: | 
          xcodebuild archive -project Kei3MapApp.xcodeproj -scheme Kei3MapApp -archivePath Kei3MapApp.xcarchive -sdk iphoneos -configuration Release CODE_SIGNING_ALLOWED=NO

      - name: Create ExportOptions.plist
        run: |
          echo '${{ secrets.EXPORT_OPTIONS }}' > ExportOptions.plist
          cat ExportOptions.plist

      - name: Create Private Key
        run: |
          mkdir private_keys
          echo -n '${{ secrets.APPLE_API_KEY_BASE64 }}' | base64 --decode > ./private_keys/AuthKey_${{ secrets.APPLE_API_ISSUER_ID }}.p8

      - name: Export IPA
        run: |
          xcodebuild -exportArchive -archivePath Kei3MapApp.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath Kei3MapApp.ipa -allowProvisioningUpdates -authenticationKeyPath `pwd`/private_keys/AuthKey_${{ secrets.APPLE_API_ISSUER_ID }}.p8 -authenticationKeyID ${{ secrets.APPLE_API_KEY_ID }} -authenticationKeyIssuerID ${{ secrets.APPLE_API_ISSUER_ID }}

      - name: Compress IPA file
        run: zip -r Kei3MapApp.zip Kei3MapApp.ipa

      - name: Upload to App Store Connect
        run: |
          xcrun notarytool submit Kei3MapApp.ipa \
            --apple-id ${{ secrets.APPLE_ID }} \
            --password ${{ secrets.APP_SPECIFIC_PASSWORD }} \
            --team-id D2B3JPR4TJ \
            --wait
